package StoreApp;


/**
* StoreApp/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Store.idl
* Friday, October 16, 2020 9:06:55 o'clock PM EDT
*/

public interface StoreOperations 
{
  String addItem (String managerID, String itemID, String itemName, String quantity, String price);
  String removeItem (String managerID, String itemID, String quantity);
  String listItemAvailability (String managerID);
  String purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID, String dateOfReturn);
  String exchangeItem (String customerID, String newItemID, String oldItemID);
  void shutdown ();
} // interface StoreOperations
